name: Build PassF0rge - Windows

on:
  push:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: |
          flutter pub get
          dart run icons_launcher:create

      - name: Install MSYS2 + GCC
        run: |
          choco install mingw -y

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Make exploits
        run: |
          cd Exploits/Windows/
          cl.exe /EHsc /std:c++17 RedSun.cpp /link ntdll.lib cldapi.lib advapi32.lib ole32.lib user32.lib /OUT:RedSun.exe
          del RedSun.cpp
          del RedSun.obj
          cd ../../

      - name: Make Exploits
        shell: cmd
        run: |
          cd Exploits/
          rmdir Linux/
          cd ..
          
      - name: Compile run.c to DLL
        shell: bash
        run: |
          gcc -shared -o run.dll run.c -Wl,--out-implib,librun.a

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Create Windows platform
        run: flutter create .

      - name: Build Flutter Windows
        run: flutter build windows --release
        
      - name: Prepare release folder
        shell: powershell
        run: |
          mkdir release
          xcopy build\windows\x64\runner\Release\* release\ /E /I /Y
          copy run.dll release\run.dll
          if (Test-Path Exploits) {
            xcopy Exploits release\Exploits\ /E /I /Y
          }

      - name: Remove source files from release
        shell: powershell
        run: |
          Get-ChildItem release -Include *.dart,*.c,*.h -Recurse | Remove-Item -Force
          flutter clean

      - name: Create ZIP
        run: |
          powershell Compress-Archive -Path release\* -DestinationPath PassF0rge.zip

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: PassF0rge-Windows
          path: PassF0rge.zip
