name: Build PassF0rge - Linux

on:
  push:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Make exploits
        run: |
          cd Exploits/
          rm -rf Windows/
          cd ..

      - name: Make Exploits
        run: |
          sudo apt install python3 -y
          pip install pyinstaller
          cd Exploits/Linux/
          pyinstaller --onefile CopyFail.py
          rm -rf build
          rm CopyFail.spec
          mv dist/CopyFail ./
          cd ../../
          
      - name: Compile run.c to DLL
        shell: bash
        run: |
          gcc -shared -o run.so run.c -Wl,--out-implib,librun.a

      - name: Install Linux dependencies
        run: |
          sudo apt update
          sudo apt install -y \
          clang \
          cmake \
          ninja-build \
          pkg-config \
          libgtk-3-dev

      - name: Enable Linux desktop
        run: flutter config --enable-linux-desktop

      - name: Create Linux platform
        run: flutter create .

      - name: Build Flutter Linux
        run: flutter build linux --release
        
      - name: Prepare release folder
        shell: bash
        run: |
          mkdir release
          mv build/linux/x64/release/bundle/* release/
          mv run.so release/run.so
          mv Exploits/ release/Exploits/
          cd release

      - name: Remove source files from release
        shell: bash
        run: |
          flutter clean
          cd ..

      - name: Create ZIP
        run: |
          zip -r PassF0rge.zip release/

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: PassF0rge
          path: PassF0rge.zip
          archive: false
